# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/07_cli.ipynb.

# %% auto 0
__all__ = ['cli', 'test']

# %% ../notebooks/07_cli.ipynb 1
import argparse
import inspect

def cli(f, descr=""):
    parser = argparse.ArgumentParser(description=f.__doc__)
    sig = inspect.signature(f)
    
    for k,v in sig.parameters.items():
        # FYI: you get the type annotation
        # via `sig.parameters[k].annotation`
        
        if v.default is inspect.Parameter.empty:
            parser.add_argument(k)  
        else:
            parser.add_argument(f"-{k}", f"--{k}", 
                                default=v.default) 
            
    def g():
        args = parser.parse_args()
        f(**vars(args))
        
    return g

# %% ../notebooks/07_cli.ipynb 2
import os
@cli
def test(x, y=2, *, z=3):
    """A docstring for this test function."""
    print(x, y, z)
